name: pertemuan2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
    lottie: ^3.1.3
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    google_fonts: ^6.2.1
    get: ^4.6.6
    dio: ^5.7.0
    flutter_svg: ^2.0.17
    shared_preferences: ^2.5.1


dev_dependencies:
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Mengaktifkan Material Icons
  uses-material-design: true

  # Menambahkan asset
  assets:
    - assets/images/
    - assets/images/internal/
    - assets/lottie/
    - assets/svg/
    - assets/svg/logos/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/static/Raleway-Medium.ttf
