name: pertemuan2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
    lottie: ^3.1.3
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    google_fonts: ^6.2.1
    get: ^4.6.6


dev_dependencies:
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Mengaktifkan Material Icons
  uses-material-design: true

  # Menambahkan asset
  assets:
    - assets/images/

flutter_native_splash:
  color: "#00623B" # terserah sesuain warna sendiri
  image: assets/images/LogoSplash.png 
  android: true
  ios: true
  web: true
